output:skipListMain.o skipList.o 
	g++ skipListMain.o skipList.o -o output

skipListMain.o: skipListMain.cpp skipList.h
	g++ -c skipListMain.cpp

skipList.o: skipList.cpp skipList.h
	g++ -c skipList.cpp